### ISSUE TITLE
Integrate cost-of-living (COLA) into calculator

### ISSUE THREAD

**Issue by davidbader** [codeforboston/windfall-elimination#21]
Cost-of-living (aka COLA) is used to offset value lost due to inflation. The COLA amount varies by year and is expressed as a percentage (i.e., like inflation) - it is driven by the consumer price index (CPI). SSA benefits are increased by the COLA amounts each year in a compounding way.

See https://www.ssa.gov/cola/ for more information.

**Comment by davidbader** [comment]
@annemeeker

**Comment by annemeeker** [comment]
COLA:
A cost-of-living adjustment (COLA) is applied to the benefit beginning in the second year of eligibility, which for retired workers is age 63. The COLA applies even if a worker has not yet begun to receive benefits.
·         See CRS Report R43542 How Social Security Benefits are Computed: In Brief, at https://www.crs.gov/Reports/R43542?source=search&guid=0b10c7430bcf46caa9c003c1563b9e8b&index=3#_Toc517944667.
 
When a COLA occurs, the PIA  is increased by the COLA first, and then adjusted for early or delayed retirement.
·         See SSA, Application of COLA to a Retirement Benefit, at https://www.ssa.gov/oact/cola/colaapplic.html.
 
When the WEP applies, the benefit is calculated as below:
(1)    Determine the AIME
(2)    Calculate the WEP PIA rounded to the lower dime (the first bend point is used based on number of years of coverage, see POMS RS 00605.362 at https://secure.ssa.gov/poms.nsf/lnx/0300605362), adjusted by COLAs if applicable
(3)    Calculate a regular PIA (at age 62) rounded to the lower dime and reduce by 50% of the applicable pension amount, adjusted by COLAs if applicable
(4)    Select the larger of (2) and (3)
If retirement occurs after age 62, in step (2), the COLA would apply to the WEP PIA amount when it is payable; and in step (3), the COLA would apply to the different amount (regular PIA-50% of non-covered pension). The above procedure applies when an individual concurrent entitled to Social Security benefits and non-covered pension benefit. For more information see POMS RS 00605.370 at https://secure.ssa.gov/poms.nsf/lnx/0300605370. The resulting amount then would be adjusted for early or delayed retirement.
 
COLA and delayed retirement credit:
Since the COLA applies to one’s PIA starting at age 63, a worker who retires after the Full Retirement Age (FRA) would receive both the COLA and the delayed retirement credit.

**Comment by annemeeker** [comment]
[R43542.pdf](https://github.com/codeforboston/windfall-elimination/files/3158110/R43542.pdf)

**Comment by davidbader** [comment]
@thadk PR via Observeable Suggestion (https://observablehq.com/compare/ebb6ecd0d81fc3bf...a658dce847fde220) for review

**Comment by thadk** [comment]
Thanks David, I sent it back to you with [this revision](https://observablehq.com/compare/a658dce847fde220...d1218150e7e7ded4) because I noticed the RetireYear was not a number and might be doing some unexpected casting/converting that acts differently than a number like 2008 would.

**Comment by davidbader** [comment]
thanks for the bug spotting @thadk. I re-published my fork to fix that issue (& closed your suggestion, is that the right way to do this? Sorry for being unfamiliar w/ observable version control). 

I wanted to maintain the contract that getAggregateCola() would always expect year values for both arguments, so I added in the missing `.year()` call inside the `getWepMpb()` definition to ensure that it passes the value in the way that the COLA function expects.

Let me know if there's anything else I can do.

**Comment by davidbader** [comment]
Suggestion Accepted & Merged into https://observablehq.com/@thadk/windfall-awareness-notebook-prototype
