### ISSUE TITLE
Lump-sum to monthly pension calculation

### ISSUE THREAD

**Issue by davidbader** [codeforboston/windfall-elimination#22]

**Comment by annemeeker** [comment]
When a beneficiary has a lump sum instead of a monthly pension, the SSA takes the lump sum and the AGE WHEN THEY CAN START TO WITHDRAW THE LUMP SUM and throw it into this table to come up with the months of their life expectancy. Then divide the lump sum by the months of the table.

Lump sum:
https://secure.ssa.gov/poms.nsf/links/0300605364

**Comment by thadk** [comment]
@supjohn implemented a first version of this here:
https://observablehq.com/d/b133f94d7388d220

and I added some comments and started to test it at:
https://observablehq.com/d/ae3303d3b57c20b0
